hide: true
order: 1
title: Testimonials
sections:
  main:
    display: Main
    fields:
      -
        handle: title
        field:
          type: text
          required: true
          validate:
            - required
          display: Name
          listable: true
          input_type: text
          antlers: false
      -
        handle: quote
        field:
          type: markdown
          localizable: true
          display: Quote
          listable: hidden
          restrict: false
          automatic_line_breaks: true
          automatic_links: false
          escape_markup: false
          smartypants: false
          antlers: false
      -
        handle: compay
        field:
          input_type: text
          antlers: false
          display: Compay
          type: text
          icon: text
          listable: hidden
  sidebar:
    display: Sidebar
    fields:
      -
        handle: slug
        field:
          type: slug
          required: true
          localizable: true
          validate:
            - required
