title: Products
template: product
route: '/products/{slug}'
structure:
  max_depth: 1
  tree:
    -
      entry: e045b4ac-d301-46f3-9a29-9eaf5aab1d2a
    -
      entry: 0c5c4f88-e0f1-4d33-bf86-b7d5c4385c85
    -
      entry: 8200310e-5a24-4b37-8779-96b23b06b43a
